#DEPARTURE/ARRIVAL;Flight number;Passengers;HH:MM;Parking (departure only);Remaining time
#This is a comment example.
#If DEPARTURE, parking must be set
#If ARRIVAL, set parking to zero
#First line must set initial time
#For example:
14:55
#Aircraft arrival (or departure) must be set relative to initial time, in HH:MM format.
ARRIVAL;PHX1002;40;00:05;0;120
ARRIVAL;PHX1802;100;01:00;0;120
ARRIVAL;PHX2015;250;00:10;0;120
DEPARTURE;PHX1000;100;00:05;19;120
DEPARTURE;PHX1280;100;00:30;19;120
